#:kivy 1.8.0

<MyWidget>:
    volumeBtn: btn_volume
    volumeSlider: slider_volume
    BoxLayout:
        size: root.size
        orientation: 'vertical'
        Slider:
            id: slider_volume
            min: 0
            max: 100
            orientation: 'vertical'
            size_hint: (1, .7)
        Button:
            id: btn_volume
            text: 'Set Volume'
            size_hint: (1, .3)
